package com.lume.client.menu;

import com.lume.client.gui.Theme;
import com.mojang.blaze3d.systems.RenderSystem;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.texture.NativeImage;
import net.minecraft.client.texture.NativeImageBackedTexture;
import net.minecraft.util.Identifier;

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

/**
 * Loads the pre-baked main-menu chrome PNGs and blits them via DrawContext —
 * zero NanoVG, crisp bilinear-filtered images.
 *
 * <p>There are SIX baked sets (theme × glass-style): {@code <light|dark>_<default|
 * fullglass|noglass>}, generated by {@code tools/gen_menu.py}. {@link #blit} picks
 * the set live from {@link Theme#isDark()} + {@link Theme#getGlassStyle()}, so the
 * whole menu re-skins the instant the user toggles theme or glass style — the sun/
 * moon icon and every panel swap together. Colours are baked (theme/custom-accent
 * doesn't recolour them beyond picking the light/dark set) — deliberate, per the
 * user's request; it's what let the menu stop rendering through NanoVG (which
 * crashed one Intel iGPU driver inside nvgEndFrame).
 *
 * <p>Frame-only assets ({@link #PILL}, {@link #ACCOUNT}, {@link #ROW}) bake just the
 * glass frame; callers draw the live text (nickname, server/friend names, toggle
 * label) on top via the normal font path.
 *
 * <p>Textures load lazily on the render thread; a load failure is cached so callers
 * cleanly fall back to their old vector path.
 */
public final class MenuAssets {
    private MenuAssets() {}

    public static final String LOGO = "logo";
    public static final String SINGLEPLAYER = "singleplayer";
    public static final String MULTIPLAYER = "multiplayer";
    public static final String OPTIONS_LANGUAGE = "box_options_language";
    public static final String QUIT = "box_quit";
    public static final String IC_THEME = "ic_theme";
    public static final String IC_COLORS = "ic_colors";
    public static final String IC_GEAR = "ic_gear";
    public static final String IC_MENU = "ic_menu";
    public static final String PILL = "pill";
    public static final String ACCOUNT = "account";
    public static final String ROW = "row";

    public static final class Tex {
        public final Identifier id;
        public final int w, h;
        Tex(Identifier id, int w, int h) { this.id = id; this.w = w; this.h = h; }
    }

    private static final Map<String, Tex> CACHE = new HashMap<>();
    private static final Map<String, Boolean> FAILED = new HashMap<>();

    /** Current baked set key from theme + glass style, e.g. {@code "dark_fullglass"}. */
    public static String currentKey() {
        String theme = Theme.isDark() ? "dark" : "light";
        int gs = Theme.getGlassStyle();
        String style = gs == 1 ? "fullglass" : gs == 2 ? "noglass" : "default";
        return theme + "_" + style;
    }

    /** Lazily load {@code menu/<key>/<name>.png}; null if unavailable or off-thread. */
    public static Tex get(String key, String name) {
        String cacheKey = key + "/" + name;
        Tex t = CACHE.get(cacheKey);
        if (t != null) return t;
        if (Boolean.TRUE.equals(FAILED.get(cacheKey))) return null;
        if (!RenderSystem.isOnRenderThread()) return null;
        try (InputStream in = MenuAssets.class.getResourceAsStream("/assets/lume/textures/menu/" + key + "/" + name + ".png")) {
            if (in == null) throw new java.io.IOException("resource missing");
            NativeImage img = NativeImage.read(in);
            NativeImageBackedTexture tex = new NativeImageBackedTexture(img);
            tex.setFilter(true, false);
            Identifier id = Identifier.of("lume", "menu_" + key + "_" + name);
            MinecraftClient.getInstance().getTextureManager().registerTexture(id, tex);
            t = new Tex(id, img.getWidth(), img.getHeight());
            CACHE.put(cacheKey, t);
            return t;
        } catch (Exception e) {
            FAILED.put(cacheKey, Boolean.TRUE);
            System.out.println("[Lume] MenuAssets: failed to load " + cacheKey + ".png: " + e);
            return null;
        }
    }

    /** Convenience: load from the current theme×style set. */
    public static Tex get(String name) { return get(currentKey(), name); }

    private static Tex glowTex;
    private static boolean glowFailed;

    /** Soft radial glow (shared {@code menu/glow.png}, white → tinted by {@code argb}) drawn over
     *  {@code (x,y,w,h)} expanded by {@code margin} on every side. Smooth premium hover glow —
     *  replaces the old layered-rect {@code RenderUtil.glow}. No-op if the sprite can't load. */
    public static void blitGlow(DrawContext ctx, int x, int y, int w, int h, int margin, int argb) {
        if (glowTex == null) {
            if (glowFailed || !RenderSystem.isOnRenderThread()) return;
            try (InputStream in = MenuAssets.class.getResourceAsStream("/assets/lume/textures/menu/glow.png")) {
                if (in == null) throw new java.io.IOException("resource missing");
                NativeImage im = NativeImage.read(in);
                NativeImageBackedTexture t = new NativeImageBackedTexture(im);
                t.setFilter(true, false);
                Identifier id = Identifier.of("lume", "menu_glow");
                MinecraftClient.getInstance().getTextureManager().registerTexture(id, t);
                glowTex = new Tex(id, im.getWidth(), im.getHeight());
            } catch (Exception e) { glowFailed = true; return; }
        }
        var ms = ctx.getMatrices();
        ms.push();
        ms.translate(x - margin, y - margin, 0);
        ms.scale((w + 2f * margin) / glowTex.w, (h + 2f * margin) / glowTex.h, 1f);
        ctx.drawTexture(RenderLayer::getGuiTextured, glowTex.id, 0, 0, 0f, 0f, glowTex.w, glowTex.h, glowTex.w, glowTex.h, argb);
        ms.pop();
    }

    /** Blit a baked texture (current set) scaled to (w,h) logical px at (x,y). Matrix-scaled
     *  1:1 blit + bilinear filter = smooth downscale from the 4x source.
     *  @return false if the texture wasn't available (caller should fall back). */
    public static boolean blit(DrawContext ctx, String name, int x, int y, int w, int h) {
        Tex t = get(currentKey(), name);
        if (t == null) return false;
        var ms = ctx.getMatrices();
        ms.push();
        ms.translate(x, y, 0);
        ms.scale(w / (float) t.w, h / (float) t.h, 1f);
        ctx.drawTexture(RenderLayer::getGuiTextured, t.id, 0, 0, 0f, 0f, t.w, t.h, t.w, t.h, 0xFFFFFFFF);
        ms.pop();
        return true;
    }
}
